### PR TITLE
Match directory structure to namespace

### PR DESCRIPTION
**Pull request by mikedfunk**
Just moved src/* to src/Demand/* to match namespacing.

* To allow adding additional namespaces <-> directories later without
having to adjust composer.json
* slightly simplifies composer.json, 
* puts classes in the expected directory from the beginning the same 
way the autoloader looks for them. 

Tests pass.

### CODE REVIEW

**Comment by mshindle** [comment]
The only issue I have with this change is that composer will look in the potato src directory for anything 'Demand' namespace related and not just those namespaces controlled by this module. When using the optimizer, this isn't an issue but if we ever opened this module up to others at Demand, it might be a problem.

Check out what Fabien Potencier does with Symfony modules...

https://github.com/symfony/finder/blob/master/composer.json

If anything, filter could be namespaced under core and all of core moved into its own composer module. It's just combined in this module because it felt too small to separate.

**Comment by mikedfunk** [comment]
But this does not move any of the common classes under the potato folder, it just matches them up to the namespaces. For instance `Demand\Core\FilteredObject` is now in `src/Demand/Core/FilteredObject`. No potato parent.

I get what you're saying about externalizing them to their own composer package though.

**Comment by mshindle** [comment]
It's the following autoload line I have issue with - not the directory structure.

```
     "autoload": {
          "psr-4": {
             "Demand\\": "src/Demand/"
          }
    }
```

This configuration tells the composer autoloader to look at potato source for anything in the Demand namespace. 

I prefer Fabien's convention of keeping the autoloader namespace as tight as possible: `"psr-4": { "Symfony\\Component\\Finder\\": "" }`.

**Comment by mikedfunk** [comment]
Per this:
> It's the following autoload line I have issue with - not the directory structure.

I mapped the lowest level namespaces to their directories. Let me know if there's anything else.

**Comment by mikedfunk** [comment]
Thanks!

**Pull request merged**
